name: Makefile CI

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest
    concurrency: release
    permissions:
      id-token: write
      contents: write

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install dependencies
        run: make

      - name: Run clean
        run: make clean

      - name: Run install-poetry
        run: make install-poetry

      - name: Install manu-sdk
        run: make install

      - name: Run lint
        run: make lint

      - name: Run psr-publish
        run: make psr-publish
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
