name: Makefile CI

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest
    concurrency: release

    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: make

      - name: Run clean
        run: make clean

      - name: Run install-poetry
        run: make install-poetry

      - name: Install manu-sdk
        run: make install

      - name: Run lint
        run: make lint

      - name: Run psr-publish
        uses: make psr-publish
        with:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
